apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jvb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/jitsi-meet.jitsi: "true"
        io.kompose.service: jvb
    spec:
      containers:
        - env:
            - name: SENTRY_DSN
              value: '"0"'
          image: jitsi/jvb:stable-9457-2
          name: jvb
          ports:
            - containerPort: 10000
              hostPort: 10000
              protocol: UDP
            - containerPort: 8080
              hostIP: 127.0.0.1
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: jvb-claim0
      restartPolicy: Always
      volumes:
        - name: jvb-claim0
          persistentVolumeClaim:
            claimName: jvb-claim0
