apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  ports:
    - name: "10000"
      port: 10000
      protocol: UDP
      targetPort: 10000
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: jvb
