apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: prosody
  name: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prosody
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/jitsi-meet.jitsi: "true"
        io.kompose.service: prosody
    spec:
      containers:
        - image: jitsi/prosody:stable-9457-2
          name: prosody
          ports:
            - containerPort: 5222
              protocol: TCP
            - containerPort: 5269
              protocol: TCP
            - containerPort: 5347
              protocol: TCP
            - containerPort: 5280
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prosody-claim0
            - mountPath: /prosody-plugins-custom
              name: prosody-claim1
      restartPolicy: Always
      volumes:
        - name: prosody-claim0
          persistentVolumeClaim:
            claimName: prosody-claim0
        - name: prosody-claim1
          persistentVolumeClaim:
            claimName: prosody-claim1
