apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/jitsi-meet.jitsi: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: jitsi/web:stable-9457-2
          name: web
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: web-claim0
            - mountPath: /var/spool/cron/crontabs
              name: web-claim1
            - mountPath: /usr/share/jitsi-meet/transcripts
              name: web-claim2
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
        - name: web-claim2
          persistentVolumeClaim:
            claimName: web-claim2
